# Generated by Django 3.0.3 on 2020-02-03 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army1_pts', models.PositiveIntegerField()),
                ('army2_pts', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('army1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_army', to='home.Army')),
                ('army2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_player_army', to='home.Army')),
            ],
        ),
        migrations.AddField(
            model_name='army',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League'),
        ),
        migrations.AddField(
            model_name='army',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
