# Generated by Django 3.0.3 on 2020-02-10 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200208_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='password',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
