# Generated by Django 3.0.3 on 2020-02-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200210_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='army',
            name='image',
            field=models.ImageField(upload_to='army'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='army1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='your_army', to='home.Army'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='army2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_player_army', to='home.Army'),
        ),
    ]
