# Generated by Django 3.0.3 on 2020-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200210_1607'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('password',), name='unique_pass'),
        ),
    ]
