# Generated by Django 3.0.3 on 2020-02-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200210_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='army1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='your_army', to='home.Army', verbose_name='Your Army'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='army1_pts',
            field=models.PositiveIntegerField(verbose_name='Your Points'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='army2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_player_army', to='home.Army', verbose_name='Enemy Army'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='army2_pts',
            field=models.PositiveIntegerField(verbose_name='Enemy Points'),
        ),
    ]
